install_state: false
env: dev
charset: utf-8
lang: fr
siteName: MonSuperBlog.fr
siteUrl: 'https://project5.tld'
fileAllowedExt:
  - jpg
  - jpeg
  - png
  - webp
  - pdf
fileAllowedMime:
  - image/png
  - image/jpeg
  - image/webp
  - application/pdf
imgUploadPath: /uploaded
