install_state: false
env: dev
charset: utf-8
lang: fr
siteName: MonSuperBlog.fr
siteUrl: 'https://project5.tld'
imgAllowedExt:
  - jpg
  - jpeg
  - png
  - webp
imgAllowedMime:
  - image/png
  - image/jpeg
  - image/webp
fileAllowedExt:
  - pdf
fileAllowedMime:
  - application/pdf
imgUploadPath: /uploaded
mailer:
  host: localhost
  username: no-reply@mywebsite.com
  password: my_strong_password
  mailer_name: No-Reply
