home:
  uri: /
  area: Public
  controller: HomeController
  action: showHome
  parameters: []

blog:
  uri: /blog
  area: Public
  controller: BlogController
  action: showBlog
  parameters: []

blogSingle:
  uri: /blog/([a-zA-Z0-9-]+)
  area: Public
  controller: BlogController
  action: showBlogSingle
  parameters: ['slug']

blogPagin:
  uri: /blog/page/([0-9]+)
  area: Public
  controller: BlogController
  action: showBlog
  parameters: ['page']

contact:
  uri: /contact
  area: Public
  controller: ContactController
  action: showContact
  parameters: []

login:
  uri: /login
  area: Public
  controller: AccountController
  action: showLogin
  parameters: []

register:
  uri: /register
  area: Public
  controller: AccountController
  action: showRegister
  parameters: []

legal:
  uri: /mentions-legales
  area: Public
  controller: HomeController
  action: showMentions
  parameters: []

rgpd:
  uri: /rgpd
  area: Public
  controller: HomeController
  action: showRGPD
  parameters: []

dashboard:
  uri: /dashboard
  area: Admin
  controller: DashboardController
  action: showDashboard
  parameters: []

articleList:
  uri: /dashboard/article/list
  area: Admin
  controller: ArticleController
  action: showArticleList
  parameters: []

articleAdd:
  uri: /dashboard/article/add
  area: Admin
  controller: ArticleController
  action: showArticleAdd
  parameters: []

articleEdit:
  uri: /dashboard/article/([0-9]+)/edit
  area: Admin
  controller: ArticleController
  action: showArticleEdit
  parameters: ['articleId']

articleDelete:
  uri: /dashboard/article/([0-9]+)/delete
  area: Admin
  controller: ArticleController
  action: deleteArticle
  parameters: ['articleId']

commentList:
  uri: /dashboard/comment/list
  area: Admin
  controller: CommentController
  action: showCommentList
  parameters: []

profile:
  uri: /dashboard/profil
  area: Admin
  controller: UserController
  action: showProfile
  parameters: []
