home:
  uri: /
  area: Public
  controller: HomeController
  action: showHome
  parameters: [ ]

blog:
  uri: /blog
  area: Public
  controller: BlogController
  action: showBlog
  parameters: [ ]

blogPagin:
  uri: /blog/page/([0-9]+)
  area: Public
  controller: BlogController
  action: showBlog
  parameters: [ 'page' ]

blogSingle:
  uri: /blog/([a-zA-Z0-9-]+)
  area: Public
  controller: BlogController
  action: showSingle
  parameters: [ 'slug' ]

blogSinglePagin:
  uri: /blog/([a-zA-Z0-9-]+)/page/([0-9]+)
  area: Public
  controller: BlogController
  action: showSingle
  parameters: [ 'slug', 'page' ]

contact:
  uri: /contact
  area: Public
  controller: ContactController
  action: showContact
  parameters: [ ]

login:
  uri: /login
  area: Public
  controller: AccountController
  action: showLogin
  parameters: [ ]

logout:
  uri: /logout
  area: Public
  controller: AccountController
  action: logout
  parameters: [ ]

register:
  uri: /register
  area: Public
  controller: AccountController
  action: showRegister
  parameters: [ ]

registerAdmin:
  uri: /registerAdmin
  area: Public
  controller: AccountController
  action: showRegisterAdmin
  parameters: [ ]

legal:
  uri: /mentions-legales
  area: Public
  controller: HomeController
  action: showMentions
  parameters: [ ]

rgpd:
  uri: /rgpd
  area: Public
  controller: HomeController
  action: showRGPD
  parameters: []

dashboard:
  uri: /dashboard
  area: Admin
  controller: DashboardController
  action: showDashboard
  parameters: [ ]

articleList:
  uri: /dashboard/article/list
  area: Admin
  controller: ArticleController
  action: readList
  parameters: [ ]

articleListPagin:
  uri: /dashboard/article/list/([0-9]+)
  area: Admin
  controller: ArticleController
  action: readList
  parameters: [ 'page' ]

articleAdd:
  uri: /dashboard/article/add
  area: Admin
  controller: ArticleController
  action: create
  parameters: [ ]

articleEdit:
  uri: /dashboard/article/([0-9]+)/edit
  area: Admin
  controller: ArticleController
  action: edit
  parameters: ['articleId']

articleDelete:
  uri: /dashboard/article/([0-9]+)/delete
  area: Admin
  controller: ArticleController
  action: delete
  parameters: [ 'articleId' ]

commentList:
  uri: /dashboard/comment/list
  area: Admin
  controller: CommentController
  action: showCommentList
  parameters: [ ]

commentListPagin:
  uri: /dashboard/comment/list/([0-9]+)
  area: Admin
  controller: CommentController
  action: showCommentList
  parameters: [ 'page' ]

commentValidate:
  uri: /dashboard/comment/([0-9]+)/(validate|suspend)
  area: Admin
  controller: CommentController
  action: validate
  parameters: [ 'commentId', 'state' ]

commentDelete:
  uri: /dashboard/comment/([0-9]+)/delete
  area: Admin
  controller: CommentController
  action: delete
  parameters: [ 'commentId' ]

profile:
  uri: /dashboard/profil
  area: Admin
  controller: UserController
  action: showProfile
  parameters: [ ]

socialNetDelete:
  uri: /dashboard/profil/network/([0-9]+)/delete
  area: Admin
  controller: UserController
  action: deleteNetwork
  parameters: [ 'networkId' ]
